/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => YBRPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  pairs: [],
  autoSync: true,
  useDisplayName: false,
  debug: false
};
function isCompletePair(pair) {
  return pair.fieldA.trim().length > 0 && pair.fieldB.trim().length > 0 && pair.tagA.trim().length > 0 && pair.tagB.trim().length > 0;
}

// src/wikilink-utils.ts
function parseWikilink(raw) {
  var _a, _b;
  const match = raw.match(/^\[\[([^\]|]+?)(?:\|([^\]]+))?\]\]$/);
  if (!match)
    return null;
  return {
    target: match[1].trim(),
    display: (_b = (_a = match[2]) == null ? void 0 : _a.trim()) != null ? _b : null
  };
}
function buildWikilink(target, display) {
  if (display && display !== target) {
    return `[[${target}|${display}]]`;
  }
  return `[[${target}]]`;
}
function extractTargets(fieldValue) {
  if (fieldValue == null)
    return [];
  if (typeof fieldValue === "string") {
    const parsed = parseWikilink(fieldValue);
    return parsed ? [parsed.target] : [];
  }
  if (Array.isArray(fieldValue)) {
    const targets = [];
    for (const item of fieldValue) {
      if (typeof item === "string") {
        const parsed = parseWikilink(item);
        if (parsed)
          targets.push(parsed.target);
      } else if (Array.isArray(item)) {
        for (const sub of item) {
          if (typeof sub === "string") {
            targets.push(sub);
          }
        }
      }
    }
    return targets;
  }
  return [];
}
function hasLinkTo(rawLinks, targetFileName) {
  return rawLinks.some((link) => {
    const parsed = parseWikilink(link);
    return parsed && parsed.target === targetFileName;
  });
}

// src/cache.ts
var RelationCache = class {
  constructor() {
    /** Map<filePath, Map<fieldName, targetFileNames[]>> */
    this.relations = /* @__PURE__ */ new Map();
    /** Map<fileName (no .md), displayName | null> */
    this.displayNames = /* @__PURE__ */ new Map();
  }
  /**
   * Build the full cache by scanning all markdown files in the vault.
   */
  buildFullCache(vault, metadataCache, watchedFields) {
    this.relations.clear();
    this.displayNames.clear();
    const files = vault.getMarkdownFiles();
    for (const file of files) {
      const cache = metadataCache.getFileCache(file);
      const fm = cache == null ? void 0 : cache.frontmatter;
      if (fm) {
        this.updateFileRelations(file.path, fm, watchedFields);
      }
      const fileName = file.basename;
      this.displayNames.set(fileName, this.resolveDisplayNameFromFm(fm));
    }
  }
  /**
   * Update relation cache for a single file.
   */
  updateFileRelations(filePath, frontmatter, watchedFields) {
    const fieldMap = /* @__PURE__ */ new Map();
    if (frontmatter) {
      for (const field of watchedFields) {
        if (field in frontmatter) {
          fieldMap.set(field, extractTargets(frontmatter[field]));
        }
      }
    }
    this.relations.set(filePath, fieldMap);
  }
  /**
   * Get cached relation targets for a file and field.
   */
  getTargets(filePath, fieldName) {
    var _a, _b;
    return (_b = (_a = this.relations.get(filePath)) == null ? void 0 : _a.get(fieldName)) != null ? _b : [];
  }
  /**
   * Get all cached relations for a file.
   */
  getFileRelations(filePath) {
    return this.relations.get(filePath);
  }
  /**
   * Update cached targets for a specific field in a file.
   * Used after plugin writes backlinks to keep cache in sync
   * and prevent cascade triggers.
   */
  setTargets(filePath, fieldName, targets) {
    let fieldMap = this.relations.get(filePath);
    if (!fieldMap) {
      fieldMap = /* @__PURE__ */ new Map();
      this.relations.set(filePath, fieldMap);
    }
    fieldMap.set(fieldName, targets);
  }
  /**
   * Get display name for a file.
   */
  getDisplayName(fileName) {
    var _a;
    return (_a = this.displayNames.get(fileName)) != null ? _a : null;
  }
  /**
   * Update display name cache for a file.
   */
  updateDisplayName(fileName, displayName) {
    this.displayNames.set(fileName, displayName);
  }
  /**
   * Find all files whose cached wikilinks resolve to the given target file.
   * Falls back to basename/suffix matching when given a plain link target.
   * Returns array of { filePath, fieldName }.
   */
  findFilesLinkingTo(target, metadataCache) {
    const results = [];
    if (typeof target === "string") {
      for (const [filePath, fieldMap] of this.relations) {
        for (const [fieldName, targets] of fieldMap) {
          if (targets.some((t2) => t2 === target || t2.endsWith("/" + target))) {
            results.push({ filePath, fieldName });
          }
        }
      }
      return results;
    }
    if (!metadataCache)
      return results;
    for (const [filePath, fieldMap] of this.relations) {
      for (const [fieldName, targets] of fieldMap) {
        for (const linkTarget of targets) {
          const resolved = metadataCache.getFirstLinkpathDest(
            linkTarget,
            filePath
          );
          if ((resolved == null ? void 0 : resolved.path) === target.path) {
            results.push({ filePath, fieldName });
            break;
          }
        }
      }
    }
    return results;
  }
  /**
   * Handle file rename: update cache keys.
   */
  handleRename(oldPath, newPath, oldName, newName) {
    const data = this.relations.get(oldPath);
    if (data) {
      this.relations.delete(oldPath);
      this.relations.set(newPath, data);
    }
    const dn = this.displayNames.get(oldName);
    if (dn !== void 0) {
      this.displayNames.delete(oldName);
      this.displayNames.set(newName, dn);
    }
  }
  /**
   * Handle file deletion: remove from cache.
   */
  handleDelete(filePath, fileName) {
    this.relations.delete(filePath);
    this.displayNames.delete(fileName);
  }
  /**
   * Resolve display name from frontmatter: title > aliases[0] > null.
   */
  resolveDisplayNameFromFm(fm) {
    if (!fm)
      return null;
    if (typeof fm.title === "string" && fm.title.length > 0) {
      return fm.title;
    }
    return null;
  }
  // --- Static helpers ---
  /**
   * Collect all unique field names from configured pairs.
   */
  static getWatchedFields(pairs) {
    const fields = /* @__PURE__ */ new Set();
    for (const pair of pairs) {
      fields.add(pair.fieldA);
      fields.add(pair.fieldB);
    }
    return fields;
  }
  /**
   * Find the counterpart field for a given field name.
   *
   * When a field appears in multiple pairs, uses source file's tags
   * to determine which pair to use:
   *   - pair (fieldA, fieldB): applies when source tag = fieldB and source field = fieldA
   *   - pair (fieldA, fieldB): applies when source tag = fieldA and source field = fieldB
   *
   * Example: Person.md (tag: Person) has Mail field
   *   - Pair Mail↔Person: field=Mail=fieldA, tag=Person=fieldB → MATCH → counterpart=Person
   *   - Pair Mail↔Domain: field=Mail=fieldA, tag=Person≠fieldB(Domain) → skip
   */
  static getCounterpartField(fieldName, pairs, sourceTags) {
    const fieldLower = fieldName.toLowerCase();
    const matches = [];
    for (const pair of pairs) {
      if (pair.fieldA.toLowerCase() === fieldLower) {
        matches.push({ counterpartField: pair.fieldB, pair, matchedSide: "A" });
      } else if (pair.fieldB.toLowerCase() === fieldLower) {
        matches.push({ counterpartField: pair.fieldA, pair, matchedSide: "B" });
      }
    }
    if (matches.length === 0)
      return null;
    if (sourceTags && sourceTags.length > 0) {
      const tagsLower = new Set(sourceTags.map((t2) => t2.toLowerCase()));
      for (const match of matches) {
        const relevantTag = match.matchedSide === "A" ? match.pair.tagA : match.pair.tagB;
        if (relevantTag && tagsLower.has(relevantTag.toLowerCase())) {
          return { counterpartField: match.counterpartField, pair: match.pair };
        }
      }
    }
    return null;
  }
  /**
   * Check if a field name already appears in any configured pair.
   */
  static isFieldInPairs(fieldName, pairs) {
    const fieldLower = fieldName.toLowerCase();
    return pairs.some(
      (p) => p.fieldA.toLowerCase() === fieldLower || p.fieldB.toLowerCase() === fieldLower
    );
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/sync.ts
var import_obsidian = require("obsidian");

// src/i18n/en.ts
var en_default = {
  // Command
  "cmd.syncAll": "Sync all bidirectional relations",
  // Notices
  "notice.syncComplete": "Sync complete: updated {0} files",
  "notice.pairCreated": "\u2705 Pair: {0} \u2194 {1}",
  "notice.fileNotFound": "\u26A0\uFE0F File not found: {0}.md",
  "notice.backlinkAdded": "\u2705 {0} \u2192 {1}: {2}",
  "notice.backlinksCreated": "\u2705 {0}: backlinks created from {1} file(s)",
  "notice.pairRemoved": "Pair removed for {0}",
  "notice.fieldUpdate": 'YBR: {0} \u2192 creating/updating "{1}" field with {2}',
  // Settings
  "settings.fullSync": "Full sync",
  "settings.fullSync.desc": "\u26A0\uFE0F Full sync detects all unpaired fields and syncs them at once. This may modify existing YAML frontmatter \u2014 please review before running.",
  "settings.fullSync.button": "Run Full Sync",
  "settings.autoSync": "Auto sync",
  "settings.autoSync.desc": "Automatically sync bidirectional relations on file modify",
  "settings.useDisplayName": "Use title as display name",
  "settings.useDisplayName.desc": "Use the title field as display text in backlinks (e.g. [[filename|title]]). When off, backlinks use filename only. Run Full Sync after changing.",
  "settings.debug": "Debug mode",
  "settings.debug.desc": "Output detailed logs to the developer console",
  "settings.relationPairs": "Relation Pairs",
  "settings.fieldA": "Field A",
  "settings.fieldB": "Field B",
  "settings.deletePair": "Delete pair",
  "settings.addPair": "+ Add Pair",
  // Modal
  "modal.title": "New relation field detected",
  "modal.hasField": '"{0}" has a "{1}" field with wikilinks.',
  "modal.question": 'When "{0}" links to another file, what field in THAT file should get the backlink?',
  "modal.currentPairs": "Current pairs ({0})",
  "modal.backlinkField": "Backlink field",
  "modal.backlinkField.desc": "The field in the TARGET file that will receive the backlink",
  "modal.sameField": "{0} (same field)",
  "modal.newFieldName": "Or type a new field name",
  "modal.newFieldPlaceholder": "leave empty to use selection above",
  "modal.save": "Save",
  "modal.ignore": "Ignore",
  "modal.editTitle": "Bidirectional Relation",
  "modal.currentlyPaired": '"{0}" is currently paired with "{1}".',
  "modal.removePair": "Remove Pair",
  "modal.close": "Close",
  "modal.addAnother": "Add another pair for this field:",
  "modal.pairTag": 'When source tag is "{0}"',
  "modal.pairTagAny": "Any tag (fallback)",
  "modal.active": "Active",
  "modal.context": "Tag: {0} \u2192 Field: {1}",
  "modal.noPairForTag": '\u26A0\uFE0F No pair configured for tag "{0}". Sync is inactive for this field on this page. Add a pair below.',
  // Settings: tag fields
  "settings.tagA": "Tag A",
  "settings.tagB": "Tag B",
  // Modal: tag-related
  "modal.counterpartTag": "Target tag",
  "modal.counterpartTag.desc": "The tag that identifies target files for this pair",
  "modal.counterpartTag.field": "Target field",
  "modal.counterpartTag.placeholder": "Enter tag",
  "modal.sourceTag": "Tag for this page",
  "modal.sourceTag.required": "This page has no tag. A tag is required to create a pair.",
  "modal.existingPairs": "Existing pairs",
  // Property buttons
  "property.paired": "Paired: {0} \u2194 {1}",
  "property.clickToSetup": "Set up bidirectional relation",
  // Context menu
  "menu.configurePair": "Configure bidirectional relation",
  "menu.editPair": "Edit bidirectional relation"
};

// src/i18n/zh-TW.ts
var zh_TW_default = {
  // 指令
  "cmd.syncAll": "\u540C\u6B65\u6240\u6709\u96D9\u5411\u95DC\u806F",
  // 通知
  "notice.syncComplete": "\u540C\u6B65\u5B8C\u6210\uFF1A\u5DF2\u66F4\u65B0 {0} \u500B\u6A94\u6848",
  "notice.pairCreated": "\u2705 \u914D\u5C0D\uFF1A{0} \u2194 {1}",
  "notice.fileNotFound": "\u26A0\uFE0F \u627E\u4E0D\u5230\u6A94\u6848\uFF1A{0}.md",
  "notice.backlinkAdded": "\u2705 {0} \u2192 {1}\uFF1A{2}",
  "notice.backlinksCreated": "\u2705 {0}\uFF1A\u5DF2\u5F9E {1} \u500B\u6A94\u6848\u5EFA\u7ACB\u53CD\u5411\u9023\u7D50",
  "notice.pairRemoved": "\u5DF2\u89E3\u9664 {0} \u7684\u914D\u5C0D",
  "notice.fieldUpdate": "YBR\uFF1A{0} \u2192 \u6B63\u5728\u5EFA\u7ACB/\u66F4\u65B0\u300C{1}\u300D\u6B04\u4F4D\uFF1A{2}",
  // 設定
  "settings.fullSync": "\u5168\u91CF\u540C\u6B65",
  "settings.fullSync.desc": "\u26A0\uFE0F \u57F7\u884C\u5168\u91CF\u540C\u6B65\u6703\u4E00\u53E3\u6C23\u5075\u6E2C\u6240\u6709\u6C92\u914D\u5C0D\u7684\u6B04\u4F4D\u4E00\u6B21\u6027\u540C\u6B65\uFF0C\u53EF\u80FD\u6703\u6539\u8B8A\u5DF2\u6709\u5167\u5BB9\u7684 YAML frontmatter\uFF0C\u4F7F\u7528\u524D\u8ACB\u52D9\u5FC5\u78BA\u8A8D\u3002",
  "settings.fullSync.button": "\u57F7\u884C\u5168\u91CF\u540C\u6B65",
  "settings.autoSync": "\u81EA\u52D5\u540C\u6B65",
  "settings.autoSync.desc": "\u6A94\u6848\u4FEE\u6539\u6642\u81EA\u52D5\u540C\u6B65\u96D9\u5411\u95DC\u806F",
  "settings.useDisplayName": "\u4F7F\u7528 title \u4F5C\u70BA\u986F\u793A\u540D\u7A31",
  "settings.useDisplayName.desc": "\u53CD\u5411\u9023\u7D50\u4F7F\u7528 title \u6B04\u4F4D\u4F5C\u70BA\u986F\u793A\u6587\u5B57\uFF08\u4F8B\u5982 [[\u6A94\u540D|title]]\uFF09\u3002\u95DC\u9589\u6642\u53EA\u986F\u793A\u6A94\u540D\u3002\u8B8A\u66F4\u5F8C\u8ACB\u57F7\u884C\u5168\u91CF\u540C\u6B65\u3002",
  "settings.debug": "\u9664\u932F\u6A21\u5F0F",
  "settings.debug.desc": "\u5728\u958B\u767C\u8005\u4E3B\u63A7\u53F0\u8F38\u51FA\u8A73\u7D30\u65E5\u8A8C",
  "settings.relationPairs": "\u6B04\u4F4D\u914D\u5C0D",
  "settings.fieldA": "\u6B04\u4F4D A",
  "settings.fieldB": "\u6B04\u4F4D B",
  "settings.deletePair": "\u522A\u9664\u914D\u5C0D",
  "settings.addPair": "+ \u65B0\u589E\u914D\u5C0D",
  // 彈窗
  "modal.title": "\u5075\u6E2C\u5230\u65B0\u7684\u95DC\u806F\u6B04\u4F4D",
  "modal.hasField": "\u300C{0}\u300D\u6709\u4E00\u500B\u5305\u542B wikilink \u7684\u300C{1}\u300D\u6B04\u4F4D\u3002",
  "modal.question": "\u7576\u300C{0}\u300D\u9023\u7D50\u5230\u53E6\u4E00\u500B\u6A94\u6848\u6642\uFF0C\u76EE\u6A19\u6A94\u6848\u7684\u54EA\u500B\u6B04\u4F4D\u61C9\u8A72\u63A5\u6536\u53CD\u5411\u9023\u7D50\uFF1F",
  "modal.currentPairs": "\u76EE\u524D\u7684\u914D\u5C0D\uFF08{0}\uFF09",
  "modal.backlinkField": "\u53CD\u5411\u9023\u7D50\u6B04\u4F4D",
  "modal.backlinkField.desc": "\u76EE\u6A19\u9801\u9762\u4E2D\u8981\u53CD\u5411\u9023\u7D50\u7684\u6B04\u4F4D",
  "modal.sameField": "{0}\uFF08\u540C\u540D\u6B04\u4F4D\uFF09",
  "modal.newFieldName": "\u6216\u8F38\u5165\u65B0\u7684\u6B04\u4F4D\u540D\u7A31",
  "modal.newFieldPlaceholder": "\u7559\u7A7A\u5247\u4F7F\u7528\u4E0A\u65B9\u9078\u64C7\u7684\u6B04\u4F4D",
  "modal.save": "\u5132\u5B58",
  "modal.ignore": "\u5FFD\u7565",
  "modal.editTitle": "\u96D9\u5411\u9023\u7D50\u8A2D\u5B9A",
  "modal.currentlyPaired": "\u300C{0}\u300D\u76EE\u524D\u8207\u300C{1}\u300D\u914D\u5C0D\u4E2D\u3002",
  "modal.removePair": "\u89E3\u9664\u914D\u5C0D",
  "modal.close": "\u95DC\u9589",
  "modal.addAnother": "\u70BA\u6B64\u6B04\u4F4D\u65B0\u589E\u914D\u5C0D\uFF1A",
  "modal.pairTag": "\u4F86\u6E90 Tag \u70BA\u300C{0}\u300D\u6642",
  "modal.pairTagAny": "\u4EFB\u4F55 Tag\uFF08\u5099\u9078\uFF09",
  "modal.active": "\u9069\u7528\u4E2D",
  "modal.context": "Tag\uFF1A{0} \u2192 \u6B04\u4F4D\uFF1A{1}",
  "modal.noPairForTag": "\u26A0\uFE0F Tag\u300C{0}\u300D\u6C92\u6709\u5C0D\u61C9\u7684\u914D\u5C0D\uFF0C\u6B64\u9801\u9762\u7684\u9019\u500B\u6B04\u4F4D\u4E0D\u6703\u540C\u6B65\u3002\u8ACB\u5728\u4E0B\u65B9\u65B0\u589E\u914D\u5C0D\u3002",
  // 設定：標籤欄位
  "settings.tagA": "Tag A",
  "settings.tagB": "Tag B",
  // 彈窗：標籤相關
  "modal.counterpartTag": "\u76EE\u6A19 Tag",
  "modal.counterpartTag.desc": "\u7528\u4F86\u8B58\u5225\u6B64\u914D\u5C0D\u76EE\u6A19\u9801\u9762\u7684 Tag",
  "modal.counterpartTag.field": "\u76EE\u6A19\u6B04\u4F4D",
  "modal.counterpartTag.placeholder": "\u8F38\u5165 Tag",
  "modal.sourceTag": "\u6B64\u9801\u9762\u7684 Tag",
  "modal.sourceTag.required": "\u6B64\u9801\u9762\u6C92\u6709 Tag\uFF0C\u9700\u8981\u8A2D\u5B9A Tag \u624D\u80FD\u5EFA\u7ACB\u914D\u5C0D\u3002",
  "modal.existingPairs": "\u5DF2\u8A2D\u5B9A\u7684\u914D\u5C0D",
  // 屬性按鈕
  "property.paired": "\u5DF2\u914D\u5C0D\uFF1A{0} \u2194 {1}",
  "property.clickToSetup": "\u8A2D\u5B9A\u96D9\u5411\u9023\u7D50",
  // 右鍵選單
  "menu.configurePair": "\u8A2D\u5B9A\u96D9\u5411\u9023\u7D50",
  "menu.editPair": "\u7DE8\u8F2F\u96D9\u5411\u9023\u7D50"
};

// src/i18n/ja.ts
var ja_default = {
  // コマンド
  "cmd.syncAll": "\u3059\u3079\u3066\u306E\u53CC\u65B9\u5411\u30EA\u30EC\u30FC\u30B7\u30E7\u30F3\u3092\u540C\u671F",
  // 通知
  "notice.syncComplete": "\u540C\u671F\u5B8C\u4E86\uFF1A{0} \u4EF6\u306E\u30D5\u30A1\u30A4\u30EB\u3092\u66F4\u65B0\u3057\u307E\u3057\u305F",
  "notice.pairCreated": "\u2705 \u30DA\u30A2\uFF1A{0} \u2194 {1}",
  "notice.fileNotFound": "\u26A0\uFE0F \u30D5\u30A1\u30A4\u30EB\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\uFF1A{0}.md",
  "notice.backlinkAdded": "\u2705 {0} \u2192 {1}\uFF1A{2}",
  "notice.backlinksCreated": "\u2705 {0}\uFF1A{1} \u4EF6\u306E\u30D5\u30A1\u30A4\u30EB\u304B\u3089\u30D0\u30C3\u30AF\u30EA\u30F3\u30AF\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F",
  "notice.pairRemoved": "{0} \u306E\u30DA\u30A2\u3092\u89E3\u9664\u3057\u307E\u3057\u305F",
  "notice.fieldUpdate": "YBR\uFF1A{0} \u2192\u300C{1}\u300D\u30D5\u30A3\u30FC\u30EB\u30C9\u3092\u4F5C\u6210/\u66F4\u65B0\u4E2D\uFF1A{2}",
  // 設定
  "settings.fullSync": "\u30D5\u30EB\u540C\u671F",
  "settings.fullSync.desc": "\u26A0\uFE0F \u30D5\u30EB\u540C\u671F\u306F\u672A\u30DA\u30A2\u306E\u30D5\u30A3\u30FC\u30EB\u30C9\u3092\u3059\u3079\u3066\u691C\u51FA\u3057\u4E00\u62EC\u540C\u671F\u3057\u307E\u3059\u3002\u65E2\u5B58\u306E YAML frontmatter \u304C\u5909\u66F4\u3055\u308C\u308B\u53EF\u80FD\u6027\u304C\u3042\u308A\u307E\u3059\u3002\u5B9F\u884C\u524D\u306B\u3054\u78BA\u8A8D\u304F\u3060\u3055\u3044\u3002",
  "settings.fullSync.button": "\u30D5\u30EB\u540C\u671F\u3092\u5B9F\u884C",
  "settings.autoSync": "\u81EA\u52D5\u540C\u671F",
  "settings.autoSync.desc": "\u30D5\u30A1\u30A4\u30EB\u5909\u66F4\u6642\u306B\u53CC\u65B9\u5411\u30EA\u30EC\u30FC\u30B7\u30E7\u30F3\u3092\u81EA\u52D5\u540C\u671F\u3059\u308B",
  "settings.useDisplayName": "title \u3092\u8868\u793A\u540D\u3068\u3057\u3066\u4F7F\u7528",
  "settings.useDisplayName.desc": "\u9006\u53C2\u7167\u30EA\u30F3\u30AF\u306B title \u30D5\u30A3\u30FC\u30EB\u30C9\u3092\u8868\u793A\u540D\u3068\u3057\u3066\u4F7F\u7528\u3059\u308B\uFF08\u4F8B: [[\u30D5\u30A1\u30A4\u30EB\u540D|title]]\uFF09\u3002\u30AA\u30D5\u306E\u5834\u5408\u306F\u30D5\u30A1\u30A4\u30EB\u540D\u306E\u307F\u3002\u5909\u66F4\u5F8C\u306F Full Sync \u3092\u5B9F\u884C\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
  "settings.debug": "\u30C7\u30D0\u30C3\u30B0\u30E2\u30FC\u30C9",
  "settings.debug.desc": "\u958B\u767A\u8005\u30B3\u30F3\u30BD\u30FC\u30EB\u306B\u8A73\u7D30\u30ED\u30B0\u3092\u51FA\u529B\u3059\u308B",
  "settings.relationPairs": "\u30EA\u30EC\u30FC\u30B7\u30E7\u30F3\u30DA\u30A2",
  "settings.fieldA": "\u30D5\u30A3\u30FC\u30EB\u30C9 A",
  "settings.fieldB": "\u30D5\u30A3\u30FC\u30EB\u30C9 B",
  "settings.deletePair": "\u30DA\u30A2\u3092\u524A\u9664",
  "settings.addPair": "+ \u30DA\u30A2\u3092\u8FFD\u52A0",
  // モーダル
  "modal.title": "\u65B0\u3057\u3044\u30EA\u30EC\u30FC\u30B7\u30E7\u30F3\u30D5\u30A3\u30FC\u30EB\u30C9\u3092\u691C\u51FA",
  "modal.hasField": "\u300C{0}\u300D\u306B wikilink \u3092\u542B\u3080\u300C{1}\u300D\u30D5\u30A3\u30FC\u30EB\u30C9\u304C\u3042\u308A\u307E\u3059\u3002",
  "modal.question": "\u300C{0}\u300D\u304C\u5225\u306E\u30D5\u30A1\u30A4\u30EB\u306B\u30EA\u30F3\u30AF\u3057\u3066\u3044\u308B\u5834\u5408\u3001\u305D\u306E\u30D5\u30A1\u30A4\u30EB\u306E\u3069\u306E\u30D5\u30A3\u30FC\u30EB\u30C9\u306B\u30D0\u30C3\u30AF\u30EA\u30F3\u30AF\u3092\u8FFD\u52A0\u3057\u307E\u3059\u304B\uFF1F",
  "modal.currentPairs": "\u73FE\u5728\u306E\u30DA\u30A2\uFF08{0}\uFF09",
  "modal.backlinkField": "\u30D0\u30C3\u30AF\u30EA\u30F3\u30AF\u30D5\u30A3\u30FC\u30EB\u30C9",
  "modal.backlinkField.desc": "\u30D0\u30C3\u30AF\u30EA\u30F3\u30AF\u3092\u53D7\u3051\u53D6\u308B\u30BF\u30FC\u30B2\u30C3\u30C8\u30D5\u30A1\u30A4\u30EB\u306E\u30D5\u30A3\u30FC\u30EB\u30C9",
  "modal.sameField": "{0}\uFF08\u540C\u540D\u30D5\u30A3\u30FC\u30EB\u30C9\uFF09",
  "modal.newFieldName": "\u307E\u305F\u306F\u65B0\u3057\u3044\u30D5\u30A3\u30FC\u30EB\u30C9\u540D\u3092\u5165\u529B",
  "modal.newFieldPlaceholder": "\u7A7A\u6B04\u306E\u5834\u5408\u306F\u4E0A\u306E\u9078\u629E\u3092\u4F7F\u7528",
  "modal.save": "\u4FDD\u5B58",
  "modal.ignore": "\u7121\u8996",
  "modal.editTitle": "\u53CC\u65B9\u5411\u30EA\u30EC\u30FC\u30B7\u30E7\u30F3\u8A2D\u5B9A",
  "modal.currentlyPaired": "\u300C{0}\u300D\u306F\u73FE\u5728\u300C{1}\u300D\u3068\u30DA\u30A2\u306B\u306A\u3063\u3066\u3044\u307E\u3059\u3002",
  "modal.removePair": "\u30DA\u30A2\u3092\u89E3\u9664",
  "modal.close": "\u9589\u3058\u308B",
  "modal.addAnother": "\u3053\u306E\u30D5\u30A3\u30FC\u30EB\u30C9\u306B\u5225\u306E\u30DA\u30A2\u3092\u8FFD\u52A0\uFF1A",
  "modal.pairTag": "\u30BD\u30FC\u30B9\u30BF\u30B0\u304C\u300C{0}\u300D\u306E\u5834\u5408",
  "modal.pairTagAny": "\u4EFB\u610F\u306E\u30BF\u30B0\uFF08\u30D5\u30A9\u30FC\u30EB\u30D0\u30C3\u30AF\uFF09",
  "modal.active": "\u9069\u7528\u4E2D",
  "modal.context": "\u30BF\u30B0\uFF1A{0} \u2192 \u30D5\u30A3\u30FC\u30EB\u30C9\uFF1A{1}",
  "modal.noPairForTag": "\u26A0\uFE0F \u30BF\u30B0\u300C{0}\u300D\u306B\u5BFE\u5FDC\u3059\u308B\u30DA\u30A2\u304C\u3042\u308A\u307E\u305B\u3093\u3002\u3053\u306E\u30DA\u30FC\u30B8\u3067\u306F\u3053\u306E\u30D5\u30A3\u30FC\u30EB\u30C9\u306F\u540C\u671F\u3055\u308C\u307E\u305B\u3093\u3002\u4E0B\u3067\u30DA\u30A2\u3092\u8FFD\u52A0\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
  // 設定：タグフィールド
  "settings.tagA": "\u30BF\u30B0 A",
  "settings.tagB": "\u30BF\u30B0 B",
  // モーダル：タグ関連
  "modal.counterpartTag": "\u30BF\u30FC\u30B2\u30C3\u30C8\u30BF\u30B0",
  "modal.counterpartTag.desc": "\u3053\u306E\u30DA\u30A2\u306E\u5BFE\u8C61\u30D5\u30A1\u30A4\u30EB\u3092\u8B58\u5225\u3059\u308B\u30BF\u30B0",
  "modal.counterpartTag.field": "\u30BF\u30FC\u30B2\u30C3\u30C8\u30D5\u30A3\u30FC\u30EB\u30C9",
  "modal.counterpartTag.placeholder": "\u30BF\u30B0\u3092\u5165\u529B",
  "modal.sourceTag": "\u3053\u306E\u30DA\u30FC\u30B8\u306E\u30BF\u30B0",
  "modal.sourceTag.required": "\u3053\u306E\u30DA\u30FC\u30B8\u306B\u30BF\u30B0\u304C\u3042\u308A\u307E\u305B\u3093\u3002\u30DA\u30A2\u3092\u4F5C\u6210\u3059\u308B\u306B\u306F\u30BF\u30B0\u304C\u5FC5\u8981\u3067\u3059\u3002",
  "modal.existingPairs": "\u65E2\u5B58\u306E\u30DA\u30A2",
  // プロパティボタン
  "property.paired": "\u30DA\u30A2\u8A2D\u5B9A\u6E08\u307F\uFF1A{0} \u2194 {1}",
  "property.clickToSetup": "\u53CC\u65B9\u5411\u30EA\u30EC\u30FC\u30B7\u30E7\u30F3\u3092\u8A2D\u5B9A",
  // コンテキストメニュー
  "menu.configurePair": "\u53CC\u65B9\u5411\u30EA\u30EC\u30FC\u30B7\u30E7\u30F3\u3092\u8A2D\u5B9A",
  "menu.editPair": "\u53CC\u65B9\u5411\u30EA\u30EC\u30FC\u30B7\u30E7\u30F3\u3092\u7DE8\u96C6"
};

// src/i18n/index.ts
var locales = {
  en: en_default,
  "zh-TW": zh_TW_default,
  ja: ja_default
};
function getLocale() {
  return localStorage.getItem("language") || "en";
}
function t(key, ...args) {
  const locale = getLocale();
  const dict = locales[locale] || locales["en"];
  let str = dict[key] || locales["en"][key] || key;
  args.forEach((arg, i) => {
    str = str.replace(`{${i}}`, arg);
  });
  return str;
}

// src/yaml-utils.ts
function splitFrontmatter(content) {
  if (!content.startsWith("---"))
    return null;
  const closingIndex = content.indexOf("\n---", 3);
  if (closingIndex === -1)
    return null;
  const yaml = content.slice(content.indexOf("\n") + 1, closingIndex);
  const afterClosing = closingIndex + 4;
  const body = content.slice(afterClosing);
  return { yaml, body };
}
function formatFieldValue(values) {
  if (values.length === 0)
    return "[]";
  return "\n" + values.map((v) => `  - "${v}"`).join("\n");
}
function isContinuationLine(line) {
  return /^\s+/.test(line) && line.trim().length > 0;
}
function findFieldRange(lines, fieldName) {
  const prefix = `${fieldName}:`;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.startsWith(prefix))
      continue;
    if (line.length > prefix.length) {
      const next = line[prefix.length];
      if (next !== " " && next !== "	")
        continue;
    }
    let end = i + 1;
    while (end < lines.length && isContinuationLine(lines[end])) {
      end++;
    }
    return { start: i, end };
  }
  return null;
}
function validateYaml(yamlStr) {
  const lines = yamlStr.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === "")
      continue;
    if (isContinuationLine(line)) {
      let prev = i - 1;
      while (prev >= 0 && lines[prev].trim() === "")
        prev--;
      if (prev >= 0 && !isContinuationLine(lines[prev])) {
        const colonIdx = lines[prev].indexOf(":");
        if (colonIdx >= 0) {
          const afterColon = lines[prev].slice(colonIdx + 1).trim();
          if (afterColon !== "") {
            return false;
          }
        }
      }
      continue;
    }
    if (!line.includes(":"))
      return false;
    if (/\][A-Za-z]/.test(line))
      return false;
  }
  return true;
}
function updateFieldInContent(content, fieldName, newValues) {
  const split = splitFrontmatter(content);
  if (!split) {
    const value = formatFieldValue(newValues);
    return `---
${fieldName}: ${value}
---
${content}`;
  }
  const { yaml, body } = split;
  const lines = yaml.split("\n");
  const range = findFieldRange(lines, fieldName);
  let newLines;
  if (range) {
    const value = formatFieldValue(newValues);
    const newFieldLine = `${fieldName}: ${value}`;
    newLines = [
      ...lines.slice(0, range.start),
      newFieldLine,
      ...lines.slice(range.end)
    ];
  } else {
    const value = formatFieldValue(newValues);
    newLines = [...lines, `${fieldName}: ${value}`];
  }
  while (newLines.length > 0 && newLines[newLines.length - 1].trim() === "") {
    newLines.pop();
  }
  const newYaml = newLines.join("\n");
  if (!validateYaml(newYaml)) {
    console.error(
      `[YBR] BLOCKED corrupt YAML write for field "${fieldName}".`,
      `rangeFound=${!!range}`,
      `valueCount=${newValues.length}`
    );
    return content;
  }
  return `---
${newYaml}
---${body}`;
}
function readFieldWikilinks(yamlString, fieldName) {
  const lines = yamlString.split("\n");
  const range = findFieldRange(lines, fieldName);
  if (!range)
    return [];
  const fieldLines = lines.slice(range.start, range.end);
  const allText = fieldLines.join(" ");
  const links = [];
  const linkRegex = /\[\[[^\]]+\]\]/g;
  let m;
  while ((m = linkRegex.exec(allText)) !== null) {
    links.push(m[0]);
  }
  return links;
}

// src/sync.ts
function extractFileTags(metadataCache, file) {
  var _a;
  const fm = (_a = metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
  if (!fm)
    return [];
  const raw = fm.tags;
  if (typeof raw === "string")
    return [raw];
  if (Array.isArray(raw))
    return raw.filter((x) => typeof x === "string");
  return [];
}
function resolveTargetFile(vault, metadataCache, linkpath, sourcePath, expectedTag) {
  const candidate = metadataCache.getFirstLinkpathDest(linkpath, sourcePath);
  if (!candidate)
    return null;
  if (!expectedTag)
    return candidate;
  const tags = extractFileTags(metadataCache, candidate);
  if (tags.length === 0)
    return candidate;
  if (tags.some((t2) => t2.toLowerCase() === expectedTag.toLowerCase()))
    return candidate;
  return null;
}
function detectChanges(filePath, fileName, currentFrontmatter, cache, pairs) {
  const changes = [];
  const watchedFields = RelationCache.getWatchedFields(pairs);
  const sourceTags = (() => {
    if (!currentFrontmatter)
      return [];
    const raw = currentFrontmatter.tags;
    if (typeof raw === "string")
      return [raw];
    if (Array.isArray(raw))
      return raw.filter((x) => typeof x === "string");
    return [];
  })();
  for (const fieldName of watchedFields) {
    const counterpart = RelationCache.getCounterpartField(fieldName, pairs, sourceTags);
    if (!counterpart)
      continue;
    const oldTargets = cache.getTargets(filePath, fieldName);
    const newTargets = currentFrontmatter ? extractTargets(currentFrontmatter[fieldName]) : [];
    const oldSet = new Set(oldTargets);
    const newSet = new Set(newTargets);
    const added = newTargets.filter((t2) => !oldSet.has(t2));
    const removed = oldTargets.filter((t2) => !newSet.has(t2));
    if (added.length > 0 || removed.length > 0) {
      changes.push({
        sourceFile: filePath,
        sourceFileName: fileName,
        fieldName,
        targetFieldName: counterpart.counterpartField,
        added,
        removed,
        autoTag: counterpart.pair.fieldA === fieldName ? counterpart.pair.tagB : counterpart.pair.tagA
      });
    }
  }
  return changes;
}
async function applyChanges(changes, vault, metadataCache, cache, syncing, debug, useDisplayName = false) {
  const modsPerFile = /* @__PURE__ */ new Map();
  for (const change of changes) {
    const sourceDisplayName = useDisplayName ? cache.getDisplayName(change.sourceFileName) : null;
    for (const targetFileName of change.added) {
      const targetFile = resolveTargetFile(vault, metadataCache, targetFileName, change.sourceFile, change.autoTag);
      if (!targetFile) {
        if (debug) {
          console.log(`[YBR] Target file not found or tag mismatch: ${targetFileName} (expected tag: ${change.autoTag}) \u2014 skipping`);
        }
        continue;
      }
      let fileMods = modsPerFile.get(targetFile.path);
      if (!fileMods) {
        fileMods = /* @__PURE__ */ new Map();
        modsPerFile.set(targetFile.path, fileMods);
      }
      let fieldMod = fileMods.get(change.targetFieldName);
      if (!fieldMod) {
        fieldMod = {
          targetFieldName: change.targetFieldName,
          addLinks: [],
          removeSourceNames: [],
          autoTag: change.autoTag
          // tag from the pair's target side
        };
        fileMods.set(change.targetFieldName, fieldMod);
      }
      const newLink = buildWikilink(change.sourceFileName, sourceDisplayName);
      fieldMod.addLinks.push(newLink);
    }
    for (const targetFileName of change.removed) {
      const targetFile = resolveTargetFile(vault, metadataCache, targetFileName, change.sourceFile, change.autoTag);
      if (!targetFile)
        continue;
      let fileMods = modsPerFile.get(targetFile.path);
      if (!fileMods) {
        fileMods = /* @__PURE__ */ new Map();
        modsPerFile.set(targetFile.path, fileMods);
      }
      let fieldMod = fileMods.get(change.targetFieldName);
      if (!fieldMod) {
        fieldMod = { targetFieldName: change.targetFieldName, addLinks: [], removeSourceNames: [] };
        fileMods.set(change.targetFieldName, fieldMod);
      }
      fieldMod.removeSourceNames.push(change.sourceFileName);
    }
  }
  for (const [filePath, fieldMods] of modsPerFile) {
    const file = vault.getAbstractFileByPath(filePath);
    if (!(file instanceof import_obsidian.TFile))
      continue;
    const finalFieldStates = /* @__PURE__ */ new Map();
    for (const [, mod] of fieldMods) {
      if (mod.addLinks.length > 0) {
        new import_obsidian.Notice(
          t("notice.fieldUpdate", file.basename, mod.targetFieldName, mod.addLinks.join(", ")),
          5e3
        );
      }
    }
    syncing.add(filePath);
    try {
      await vault.process(file, (content) => {
        let result = content;
        for (const [, mod] of fieldMods) {
          const yaml = extractYaml(result);
          const existingLinks = readFieldWikilinks(yaml, mod.targetFieldName);
          let updatedLinks = [...existingLinks];
          for (const newLink of mod.addLinks) {
            const match = newLink.match(/\[\[([^\]|]+)/);
            const sourceName = match ? match[1] : "";
            if (!hasLinkTo(updatedLinks, sourceName)) {
              updatedLinks.push(newLink);
            }
          }
          for (const sourceName of mod.removeSourceNames) {
            updatedLinks = updatedLinks.filter((link) => {
              const m = link.match(/\[\[([^\]|]+)/);
              return !(m && m[1] === sourceName);
            });
          }
          if (updatedLinks.length !== existingLinks.length || updatedLinks.some((l, i) => l !== existingLinks[i])) {
            result = updateFieldInContent(result, mod.targetFieldName, updatedLinks);
          }
          finalFieldStates.set(
            mod.targetFieldName,
            updatedLinks.map((l) => {
              const m = l.match(/\[\[([^\]|]+)/);
              return m ? m[1] : "";
            }).filter(Boolean)
          );
        }
        const split = splitFrontmatter(result);
        if (split) {
          const yamlStr = split.yaml;
          const hasTagsField = yamlStr.split("\n").some(
            (line) => line.startsWith("tags:") || line.startsWith("tags :")
          );
          if (!hasTagsField) {
            for (const [, m] of fieldMods) {
              if (m.autoTag) {
                result = result.replace(
                  /^(---\n)/,
                  `---
tags:
  - ${m.autoTag}
`
                );
                if (debug) {
                  console.log(`[YBR] Auto-tagged ${filePath} with "${m.autoTag}"`);
                }
                break;
              }
            }
          }
        }
        return result;
      });
      for (const [fieldName, targets] of finalFieldStates) {
        cache.setTargets(filePath, fieldName, targets);
      }
      if (debug) {
        for (const [, mod] of fieldMods) {
          if (mod.addLinks.length > 0) {
            console.log(`[YBR] Added to ${filePath} \u2192 ${mod.targetFieldName}: ${mod.addLinks.join(", ")}`);
          }
          if (mod.removeSourceNames.length > 0) {
            console.log(`[YBR] Removed from ${filePath} \u2192 ${mod.targetFieldName}: ${mod.removeSourceNames.join(", ")}`);
          }
        }
        console.log(`[YBR] Cache updated for ${filePath}:`, Object.fromEntries(finalFieldStates));
      }
    } finally {
      setTimeout(() => syncing.delete(filePath), 500);
    }
  }
}
async function fullSync(vault, metadataCache, cache, pairs, syncing, debug, useDisplayName = false) {
  var _a, _b, _c, _d;
  const watchedFields = RelationCache.getWatchedFields(pairs);
  cache.buildFullCache(vault, metadataCache, watchedFields);
  let modifiedCount = 0;
  const files = vault.getMarkdownFiles();
  const modsPerFile = /* @__PURE__ */ new Map();
  const rewritesPerFile = /* @__PURE__ */ new Map();
  for (const file of files) {
    const fm = (_a = metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if (!fm)
      continue;
    const fmTags = (() => {
      const raw = fm.tags;
      if (typeof raw === "string")
        return [raw];
      if (Array.isArray(raw))
        return raw.filter((x) => typeof x === "string");
      return [];
    })();
    for (const fieldName of watchedFields) {
      const counterpart = RelationCache.getCounterpartField(fieldName, pairs, fmTags);
      if (!counterpart)
        continue;
      const targets = extractTargets(fm[fieldName]);
      const sourceDisplayName = useDisplayName ? cache.getDisplayName(file.basename) : null;
      const expectedTargetTag = counterpart.pair.fieldA === fieldName ? counterpart.pair.tagB : counterpart.pair.tagA;
      for (const targetFileName of targets) {
        const targetFile = resolveTargetFile(vault, metadataCache, targetFileName, file.path, expectedTargetTag);
        if (!targetFile)
          continue;
        const targetFm = (_b = metadataCache.getFileCache(targetFile)) == null ? void 0 : _b.frontmatter;
        const existingTargets = extractTargets(targetFm == null ? void 0 : targetFm[counterpart.counterpartField]);
        if (!existingTargets.includes(file.basename)) {
          const newLink = buildWikilink(file.basename, sourceDisplayName);
          let fileMods = modsPerFile.get(targetFile.path);
          if (!fileMods) {
            fileMods = /* @__PURE__ */ new Map();
            modsPerFile.set(targetFile.path, fileMods);
          }
          const existing = (_c = fileMods.get(counterpart.counterpartField)) != null ? _c : [];
          existing.push(newLink);
          fileMods.set(counterpart.counterpartField, existing);
        }
      }
    }
  }
  for (const file of files) {
    const fm = (_d = metadataCache.getFileCache(file)) == null ? void 0 : _d.frontmatter;
    if (!fm)
      continue;
    const rawContent = await vault.cachedRead(file);
    const yaml = extractYaml(rawContent);
    for (const fieldName of watchedFields) {
      const existingLinks = readFieldWikilinks(yaml, fieldName);
      if (existingLinks.length === 0)
        continue;
      let changed = false;
      const updatedLinks = existingLinks.map((link) => {
        var _a2, _b2;
        const parsed = link.match(/^\[\[([^\]|]+?)(?:\|([^\]]+))?\]\]$/);
        if (!parsed)
          return link;
        const target = parsed[1].trim();
        const currentDisplay = (_b2 = (_a2 = parsed[2]) == null ? void 0 : _a2.trim()) != null ? _b2 : null;
        const targetBasename = target.split("/").pop() || target;
        const targetTitle = cache.getDisplayName(targetBasename);
        if (useDisplayName) {
          if (targetTitle && targetTitle !== target) {
            const expected = buildWikilink(target, targetTitle);
            if (expected !== link) {
              changed = true;
              return expected;
            }
          }
        } else {
          if (currentDisplay && currentDisplay === targetTitle) {
            changed = true;
            return buildWikilink(target);
          }
        }
        return link;
      });
      if (changed) {
        let fileRewrites = rewritesPerFile.get(file.path);
        if (!fileRewrites) {
          fileRewrites = /* @__PURE__ */ new Map();
          rewritesPerFile.set(file.path, fileRewrites);
        }
        fileRewrites.set(fieldName, updatedLinks.map((l, i) => ({
          from: existingLinks[i],
          to: l
        })).filter((r) => r.from !== r.to));
      }
    }
  }
  const allFilePaths = /* @__PURE__ */ new Set([...modsPerFile.keys(), ...rewritesPerFile.keys()]);
  for (const filePath of allFilePaths) {
    const file = vault.getAbstractFileByPath(filePath);
    if (!(file instanceof import_obsidian.TFile))
      continue;
    const addMods = modsPerFile.get(filePath);
    const rewriteMods = rewritesPerFile.get(filePath);
    syncing.add(filePath);
    try {
      await vault.process(file, (content) => {
        let result = content;
        if (addMods) {
          for (const [fieldName, linksToAdd] of addMods) {
            const yaml = extractYaml(result);
            const existingLinks = readFieldWikilinks(yaml, fieldName);
            let updatedLinks = [...existingLinks];
            for (const newLink of linksToAdd) {
              const match = newLink.match(/\[\[([^\]|]+)/);
              const sourceName = match ? match[1] : "";
              if (!hasLinkTo(updatedLinks, sourceName)) {
                updatedLinks.push(newLink);
              }
            }
            if (updatedLinks.length !== existingLinks.length) {
              result = updateFieldInContent(result, fieldName, updatedLinks);
            }
          }
        }
        if (rewriteMods) {
          for (const [fieldName, rewrites] of rewriteMods) {
            const yaml = extractYaml(result);
            const existingLinks = readFieldWikilinks(yaml, fieldName);
            const updatedLinks = existingLinks.map((link) => {
              const rewrite = rewrites.find((r) => r.from === link);
              return rewrite ? rewrite.to : link;
            });
            if (updatedLinks.some((l, i) => l !== existingLinks[i])) {
              result = updateFieldInContent(result, fieldName, updatedLinks);
            }
          }
        }
        return result;
      });
      modifiedCount++;
    } finally {
      setTimeout(() => syncing.delete(filePath), 500);
    }
  }
  cache.buildFullCache(vault, metadataCache, watchedFields);
  return modifiedCount;
}
function extractYaml(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  return match ? match[1] : "";
}

// src/settings.ts
function collectExistingTags(app) {
  var _a;
  const tagSet = /* @__PURE__ */ new Set();
  const files = app.vault.getMarkdownFiles();
  for (const file of files) {
    const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if (!fm)
      continue;
    const raw = fm.tags;
    if (typeof raw === "string")
      tagSet.add(raw);
    else if (Array.isArray(raw)) {
      for (const tag of raw) {
        if (typeof tag === "string")
          tagSet.add(tag);
      }
    }
  }
  return Array.from(tagSet).sort();
}
function collectExistingFields(app) {
  var _a;
  const SYSTEM = /* @__PURE__ */ new Set(["title", "aliases", "tags", "cssclasses", "publish", "permalink", "description", "image", "cover", "banner", "date", "created", "updated", "modified", "position"]);
  const fieldSet = /* @__PURE__ */ new Set();
  const files = app.vault.getMarkdownFiles();
  for (const file of files) {
    const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if (!fm)
      continue;
    for (const key of Object.keys(fm)) {
      if (!SYSTEM.has(key) && key !== "position")
        fieldSet.add(key);
    }
  }
  return Array.from(fieldSet).sort();
}
var YBRSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName(t("settings.fullSync")).setDesc(t("settings.fullSync.desc")).addButton(
      (btn) => btn.setButtonText(t("settings.fullSync.button")).onClick(async () => {
        btn.setDisabled(true);
        btn.setButtonText("...");
        const count = await fullSync(
          this.app.vault,
          this.app.metadataCache,
          this.plugin.cache,
          this.plugin.getActivePairs(),
          this.plugin.syncing,
          this.plugin.settings.debug,
          this.plugin.settings.useDisplayName
        );
        new import_obsidian2.Notice(t("notice.syncComplete", String(count)));
        btn.setDisabled(false);
        btn.setButtonText(t("settings.fullSync.button"));
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.autoSync")).setDesc(t("settings.autoSync.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
        this.plugin.settings.autoSync = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.useDisplayName")).setDesc(t("settings.useDisplayName.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useDisplayName).onChange(async (value) => {
        this.plugin.settings.useDisplayName = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName(t("settings.debug")).setDesc(t("settings.debug.desc")).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.debug).onChange(async (value) => {
        this.plugin.settings.debug = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: t("settings.relationPairs") });
    const tags = collectExistingTags(this.app);
    const fields = collectExistingFields(this.app);
    const tagListId = "ybr-datalist-tags";
    const fieldListId = "ybr-datalist-fields";
    let tagList = containerEl.querySelector(`#${tagListId}`);
    if (!tagList) {
      tagList = containerEl.createEl("datalist", { attr: { id: tagListId } });
      for (const tag of tags) {
        tagList.createEl("option", { attr: { value: tag } });
      }
    }
    let fieldList = containerEl.querySelector(`#${fieldListId}`);
    if (!fieldList) {
      fieldList = containerEl.createEl("datalist", { attr: { id: fieldListId } });
      for (const field of fields) {
        fieldList.createEl("option", { attr: { value: field } });
      }
    }
    const headerRow = containerEl.createDiv({ cls: "ybr-settings-pair-row ybr-settings-header" });
    headerRow.createEl("span", { cls: "ybr-settings-header-tag", text: "Tag" });
    headerRow.createEl("span", { cls: "ybr-settings-header-field", text: "Field" });
    headerRow.createEl("span", { cls: "ybr-settings-arrow", text: "" });
    headerRow.createEl("span", { cls: "ybr-settings-header-field", text: "Field" });
    headerRow.createEl("span", { cls: "ybr-settings-header-tag", text: "Tag" });
    headerRow.createEl("span", { cls: "ybr-settings-header-delete", text: "" });
    const pairsContainer = containerEl.createDiv();
    const renderPairs = () => {
      pairsContainer.empty();
      this.plugin.settings.pairs.forEach((pair, index) => {
        const row = pairsContainer.createDiv({ cls: "ybr-settings-pair-row" });
        const tagAInput = row.createEl("input", {
          cls: "ybr-settings-input ybr-settings-tag",
          attr: { type: "text", placeholder: "Tag", value: pair.tagA || "", list: tagListId }
        });
        if (!pair.tagA)
          tagAInput.style.borderColor = "var(--text-error)";
        tagAInput.addEventListener("change", async () => {
          this.plugin.settings.pairs[index].tagA = tagAInput.value.trim();
          tagAInput.style.borderColor = tagAInput.value.trim() ? "" : "var(--text-error)";
          await this.plugin.saveSettings();
          this.plugin.rebuildCache();
        });
        const fieldAInput = row.createEl("input", {
          cls: "ybr-settings-input ybr-settings-field",
          attr: { type: "text", placeholder: "Field", value: pair.fieldA || "", list: fieldListId }
        });
        fieldAInput.addEventListener("change", async () => {
          this.plugin.settings.pairs[index].fieldA = fieldAInput.value.trim();
          await this.plugin.saveSettings();
          this.plugin.rebuildCache();
        });
        row.createEl("span", { cls: "ybr-settings-arrow", text: "\u2194" });
        const fieldBInput = row.createEl("input", {
          cls: "ybr-settings-input ybr-settings-field",
          attr: { type: "text", placeholder: "Field", value: pair.fieldB || "", list: fieldListId }
        });
        fieldBInput.addEventListener("change", async () => {
          this.plugin.settings.pairs[index].fieldB = fieldBInput.value.trim();
          await this.plugin.saveSettings();
          this.plugin.rebuildCache();
        });
        const tagBInput = row.createEl("input", {
          cls: "ybr-settings-input ybr-settings-tag",
          attr: { type: "text", placeholder: "Tag", value: pair.tagB || "", list: tagListId }
        });
        if (!pair.tagB)
          tagBInput.style.borderColor = "var(--text-error)";
        tagBInput.addEventListener("change", async () => {
          this.plugin.settings.pairs[index].tagB = tagBInput.value.trim();
          tagBInput.style.borderColor = tagBInput.value.trim() ? "" : "var(--text-error)";
          await this.plugin.saveSettings();
          this.plugin.rebuildCache();
        });
        const deleteBtn = row.createEl("button", { cls: "ybr-settings-delete", text: "\xD7" });
        deleteBtn.setAttribute("aria-label", t("settings.deletePair"));
        deleteBtn.addEventListener("click", async () => {
          this.plugin.settings.pairs.splice(index, 1);
          await this.plugin.saveSettings();
          this.plugin.rebuildCache();
          renderPairs();
        });
      });
      const addRow = pairsContainer.createDiv({ cls: "ybr-settings-add-row" });
      const addBtn = addRow.createEl("button", { cls: "mod-cta", text: t("settings.addPair") });
      addBtn.addEventListener("click", async () => {
        this.plugin.settings.pairs.push({ fieldA: "", fieldB: "", tagA: "", tagB: "" });
        await this.plugin.saveSettings();
        renderPairs();
      });
    };
    renderPairs();
  }
};

// src/display-name.ts
var import_obsidian3 = require("obsidian");
function resolveDisplayName(frontmatter) {
  if (!frontmatter)
    return null;
  if (typeof frontmatter.title === "string" && frontmatter.title.length > 0) {
    return frontmatter.title;
  }
  return null;
}

// src/pair-suggest-modal.ts
var import_obsidian4 = require("obsidian");
var SYSTEM_FIELDS = /* @__PURE__ */ new Set([
  "title",
  "aliases",
  "tags",
  "cssclasses",
  "publish",
  "permalink",
  "description",
  "image",
  "cover",
  "banner",
  "date",
  "created",
  "updated",
  "modified",
  "position"
]);
function collectExistingFields2(app, excludeField) {
  var _a;
  const fieldSet = /* @__PURE__ */ new Set();
  const files = app.vault.getMarkdownFiles();
  for (const file of files) {
    const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if (!fm)
      continue;
    for (const key of Object.keys(fm)) {
      if (SYSTEM_FIELDS.has(key))
        continue;
      if (key === excludeField)
        continue;
      if (key === "position")
        continue;
      fieldSet.add(key);
    }
  }
  return Array.from(fieldSet).sort();
}
function collectExistingTags2(app) {
  var _a;
  const tagSet = /* @__PURE__ */ new Set();
  const files = app.vault.getMarkdownFiles();
  for (const file of files) {
    const fm = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    if (!fm)
      continue;
    const raw = fm.tags;
    if (typeof raw === "string") {
      tagSet.add(raw);
    } else if (Array.isArray(raw)) {
      for (const tag of raw) {
        if (typeof tag === "string")
          tagSet.add(tag);
      }
    }
  }
  return Array.from(tagSet).sort();
}
var PairSuggestModal = class extends import_obsidian4.Modal {
  constructor(app, fieldName, fileName, existingPairs, sourceTags, pageFields, resolve) {
    super(app);
    this.cleanupFns = [];
    this.fieldName = fieldName;
    this.fileName = fileName;
    this.existingPairs = existingPairs;
    this.sourceTags = sourceTags;
    this.pageFields = pageFields;
    this.resolve = resolve;
    this.counterpartValue = fieldName;
    this.counterpartTagValue = "";
    this.sourceTagValue = sourceTags[0] || "";
  }
  onOpen() {
    var _a;
    const { contentEl } = this;
    contentEl.addClass("ybr-modal");
    contentEl.createEl("h3", {
      text: t("modal.editTitle"),
      attr: { style: "text-align: center; margin-bottom: 16px;" }
    });
    const fieldPairs = this.existingPairs.filter(
      (p) => p.fieldA === this.fieldName || p.fieldB === this.fieldName
    );
    const activeResult = RelationCache.getCounterpartField(
      this.fieldName,
      this.existingPairs,
      this.sourceTags
    );
    const activePair = (_a = activeResult == null ? void 0 : activeResult.pair) != null ? _a : null;
    if (fieldPairs.length > 0) {
      contentEl.createEl("p", {
        text: t("modal.existingPairs"),
        attr: { style: "font-weight: 600; font-size: 0.9em; margin-bottom: 8px; color: var(--text-muted);" }
      });
      for (const pair of fieldPairs) {
        const isActive = activePair === pair;
        const row = contentEl.createDiv({ cls: "ybr-pair-row" + (isActive ? " is-active" : "") });
        const left = row.createDiv({ cls: "ybr-pair-content" });
        left.createEl("span", { cls: "ybr-tag-badge", text: pair.tagA || "\u2014" });
        left.createEl("span", {
          cls: "ybr-field-name" + (isActive && pair.fieldA === this.fieldName ? " is-active" : ""),
          text: ` ${pair.fieldA} `
        });
        left.createEl("span", { cls: "ybr-arrow", text: "\u2194" });
        left.createEl("span", {
          cls: "ybr-field-name" + (isActive && pair.fieldB === this.fieldName ? " is-active" : ""),
          text: ` ${pair.fieldB} `
        });
        left.createEl("span", { cls: "ybr-tag-badge", text: pair.tagB || "\u2014" });
        if (isActive) {
          left.createEl("span", { cls: "ybr-active-badge", text: t("modal.active") });
        }
        const counterpart = pair.fieldA === this.fieldName ? pair.fieldB : pair.fieldA;
        const deleteBtn = row.createEl("button", { cls: "ybr-delete-btn", text: "\xD7" });
        deleteBtn.addEventListener("click", () => {
          this.resolve({ action: "remove", counterpartField: counterpart });
          this.close();
        });
      }
    }
    if (!activePair && this.sourceTags.length > 0) {
      contentEl.createEl("p", {
        text: t("modal.noPairForTag", this.sourceTags.join(", ")),
        attr: { style: "color: var(--color-red); font-size: 0.85em; margin: 8px 0;" }
      });
    }
    contentEl.createEl("hr");
    contentEl.createEl("p", {
      text: t("modal.addAnother"),
      attr: { style: "font-weight: 600; font-size: 0.9em; margin-bottom: 8px; color: var(--text-muted);" }
    });
    this.renderAddForm(contentEl);
  }
  renderAddForm(contentEl) {
    const existingFields = collectExistingFields2(this.app, this.fieldName);
    const existingTags = collectExistingTags2(this.app);
    const currentTag = this.sourceTags[0] || "";
    const addRow = contentEl.createDiv({ cls: "ybr-add-row" });
    const leftSide = addRow.createDiv({ cls: "ybr-add-left" });
    if (currentTag) {
      leftSide.createEl("span", { cls: "ybr-tag-badge ybr-active-tag", text: currentTag });
    }
    leftSide.createEl("span", {
      cls: "ybr-field-name is-active",
      text: ` ${this.fieldName} `
    });
    leftSide.createEl("span", { cls: "ybr-arrow", text: "\u2194" });
    const rightSide = addRow.createDiv({ cls: "ybr-add-right" });
    const fieldCol = rightSide.createDiv({ cls: "ybr-add-col" });
    this.createCombo(fieldCol, existingFields, t("modal.counterpartTag.field"), (val) => {
      this.counterpartValue = val;
    });
    fieldCol.createEl("span", { cls: "ybr-select-label", text: t("modal.counterpartTag.field") });
    const tagCol = rightSide.createDiv({ cls: "ybr-add-col" });
    this.createCombo(tagCol, existingTags, t("modal.counterpartTag"), (val) => {
      this.counterpartTagValue = val;
    });
    tagCol.createEl("span", { cls: "ybr-select-label", text: t("modal.counterpartTag") });
    if (this.sourceTags.length === 0) {
      contentEl.createEl("hr");
      contentEl.createEl("p", {
        text: t("modal.sourceTag.required"),
        attr: { style: "color: var(--color-red); font-size: 0.85em;" }
      });
      const sourceTagRow = contentEl.createDiv({ cls: "ybr-add-row" });
      sourceTagRow.createEl("span", {
        cls: "ybr-add-label",
        text: t("modal.sourceTag")
      });
      const sourceCol = sourceTagRow.createDiv({ cls: "ybr-add-col" });
      this.createCombo(sourceCol, existingTags, t("modal.counterpartTag.placeholder"), (val) => {
        this.sourceTagValue = val;
      });
    }
    contentEl.createEl("hr");
    const btnRow = contentEl.createDiv({ cls: "ybr-btn-row" });
    const saveBtn = btnRow.createEl("button", { cls: "mod-cta", text: t("modal.save") });
    saveBtn.addEventListener("click", () => {
      if (!this.counterpartValue)
        return;
      if (!this.counterpartTagValue)
        return;
      if (this.sourceTags.length === 0 && !this.sourceTagValue)
        return;
      this.resolve({
        action: "save",
        counterpartField: this.counterpartValue,
        counterpartTag: this.counterpartTagValue,
        sourceTag: this.sourceTagValue || void 0
      });
      this.close();
    });
    const closeBtn = btnRow.createEl("button", { text: t("modal.close") });
    closeBtn.addEventListener("click", () => {
      this.resolve({ action: "ignore" });
      this.close();
    });
  }
  /**
   * Create a combo box (input + dropdown) inside a container.
   */
  createCombo(container, options, placeholder, onChange) {
    const combo = container.createDiv({ cls: "ybr-combo" });
    const input = combo.createEl("input", {
      cls: "ybr-combo-input",
      attr: { type: "text", placeholder }
    });
    const arrow = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    arrow.setAttribute("class", "ybr-combo-arrow");
    arrow.setAttribute("viewBox", "0 0 12 12");
    const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute("d", "M3 5l3 3 3-3");
    path.setAttribute("fill", "none");
    path.setAttribute("stroke", "currentColor");
    path.setAttribute("stroke-width", "1.5");
    arrow.appendChild(path);
    combo.appendChild(arrow);
    const dropdown = combo.createDiv({ cls: "ybr-combo-dropdown" });
    const optEls = [];
    for (const opt of options) {
      const el = dropdown.createDiv({ cls: "ybr-combo-option", attr: { "data-value": opt } });
      el.textContent = opt;
      optEls.push(el);
    }
    const filterOptions = (query) => {
      const q = query.toLowerCase();
      for (const el of optEls) {
        el.style.display = (el.dataset.value || "").toLowerCase().includes(q) ? "" : "none";
      }
    };
    combo.addEventListener("mousedown", (e) => {
      if (e.target.closest(".ybr-combo-option"))
        return;
      e.preventDefault();
      input.focus();
      if (dropdown.style.display === "block") {
        dropdown.style.display = "none";
      } else {
        dropdown.style.display = "block";
        filterOptions(input.value);
      }
    });
    input.addEventListener("input", () => {
      dropdown.style.display = "block";
      filterOptions(input.value);
      onChange(input.value.trim());
    });
    for (const el of optEls) {
      el.addEventListener("mousedown", (e) => {
        e.preventDefault();
        e.stopPropagation();
        input.value = el.dataset.value || "";
        dropdown.style.display = "none";
        onChange(input.value);
      });
    }
    const onDocMousedown = (e) => {
      if (!combo.contains(e.target)) {
        dropdown.style.display = "none";
      }
    };
    document.addEventListener("mousedown", onDocMousedown);
    this.cleanupFns.push(() => document.removeEventListener("mousedown", onDocMousedown));
  }
  onClose() {
    for (const fn of this.cleanupFns)
      fn();
    this.cleanupFns = [];
    this.contentEl.empty();
    this.resolve({ action: "ignore" });
  }
};
function showPairSuggestModal(app, fieldName, fileName, existingPairs, sourceTags = [], pageFields = []) {
  return new Promise((resolve) => {
    let resolved = false;
    const wrappedResolve = (result) => {
      if (!resolved) {
        resolved = true;
        resolve(result);
      }
    };
    new PairSuggestModal(app, fieldName, fileName, existingPairs, sourceTags, pageFields, wrappedResolve).open();
  });
}

// src/menu-manager.ts
var import_obsidian5 = require("obsidian");
var MenuManager = class {
  constructor() {
    this.menu = null;
    this.queuedActions = [];
    const manager = this;
    import_obsidian5.Menu.prototype.showAtPosition = new Proxy(import_obsidian5.Menu.prototype.showAtPosition, {
      apply(showAtPosition, menu, args) {
        manager.menu = menu;
        if (manager.queuedActions.length > 0) {
          manager.runQueuedActions();
        }
        return showAtPosition.apply(menu, args);
      }
    });
  }
  runQueuedActions() {
    const actions = this.queuedActions;
    this.queuedActions = [];
    for (const action of actions)
      action();
  }
  addItem(callback) {
    if (this.menu) {
      this.menu.addItem(callback);
    } else {
      this.queuedActions.push(() => this.addItem(callback));
    }
    return this;
  }
  flush() {
    this.queuedActions.length = 0;
  }
  closeAndFlush() {
    var _a;
    (_a = this.menu) == null ? void 0 : _a.close();
    this.menu = null;
    this.flush();
  }
};

// src/main.ts
function extractYaml2(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  return match ? match[1] : "";
}
var _YBRPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.cache = new RelationCache();
    this.syncing = /* @__PURE__ */ new Set();
    this.debounceTimers = /* @__PURE__ */ new Map();
    this.layoutReady = false;
  }
  async onload() {
    await this.loadSettings();
    this.menuManager = new MenuManager();
    this.addSettingTab(new YBRSettingTab(this.app, this));
    this.addCommand({
      id: "sync-all-bidirectional-relations",
      name: t("cmd.syncAll"),
      callback: async () => {
        const count = await fullSync(
          this.app.vault,
          this.app.metadataCache,
          this.cache,
          this.getActivePairs(),
          this.syncing,
          this.settings.debug,
          this.settings.useDisplayName
        );
        new import_obsidian6.Notice(t("notice.syncComplete", String(count)));
      }
    });
    this.app.workspace.onLayoutReady(() => {
      this.rebuildCache();
      setTimeout(() => {
        this.layoutReady = true;
        if (this.settings.debug) {
          console.log("[YBR] Layout ready, accepting file events");
        }
      }, 2e3);
    });
    this.registerDomEvent(document, "click", (evt) => {
      const target = evt.target;
      if (!target)
        return;
      if (target.closest(".metadata-property-icon")) {
        this.queuePropertyMenuItems(target);
      }
    }, true);
    this.registerDomEvent(document, "contextmenu", (evt) => {
      const target = evt.target;
      if (!target)
        return;
      if (target.closest(".metadata-property-icon") || target.closest(".metadata-property")) {
        this.queuePropertyMenuItems(target);
      }
    }, true);
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          this.debouncedOnFileModify(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          this.onFileCreate(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        var _a;
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          const oldName = (_a = oldPath.split("/").pop()) == null ? void 0 : _a.replace(/\.md$/, "");
          if (oldName) {
            this.cache.handleRename(
              oldPath,
              file.path,
              oldName,
              file.basename
            );
            if (this.settings.debug) {
              console.log(
                `[YBR] Renamed: ${oldPath} \u2192 ${file.path}`
              );
            }
          }
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          this.cache.handleDelete(file.path, file.basename);
          if (this.settings.debug) {
            console.log(`[YBR] Deleted from cache: ${file.path}`);
          }
        }
      })
    );
  }
  onunload() {
    for (const timer of this.debounceTimers.values()) {
      clearTimeout(timer);
    }
    this.debounceTimers.clear();
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
    let migrated = false;
    for (const pair of this.settings.pairs) {
      if (pair.tagA === void 0) {
        pair.tagA = pair.fieldB;
        migrated = true;
      }
      if (pair.tagB === void 0) {
        pair.tagB = pair.fieldA;
        migrated = true;
      }
    }
    if (this.settings.autoUpdateDisplayName !== void 0) {
      delete this.settings.autoUpdateDisplayName;
      migrated = true;
    }
    if (migrated) {
      await this.saveData(this.settings);
    }
  }
  async saveSettings() {
    await this.saveData({
      ...this.settings,
      pairs: this.getActivePairs()
    });
  }
  getActivePairs() {
    return this.settings.pairs.filter(isCompletePair);
  }
  /**
   * Rebuild the in-memory cache. Called on startup and when settings change.
   */
  rebuildCache() {
    const activePairs = this.getActivePairs();
    const watchedFields = RelationCache.getWatchedFields(
      activePairs
    );
    this.cache.buildFullCache(
      this.app.vault,
      this.app.metadataCache,
      watchedFields
    );
  }
  // ─── Property Buttons ───────────────────────────────────────
  // ─── Context menu on properties ──────────────────────────────
  /**
   * Queue a menu item to be added to Obsidian's native property menu.
   * The MenuManager's Proxy on Menu.showAtPosition will add it when
   * the native menu is about to open.
   */
  queuePropertyMenuItems(target) {
    var _a;
    const propEl = target.closest(".metadata-property");
    if (!propEl)
      return;
    const fieldName = propEl.getAttribute("data-property-key");
    if (!fieldName)
      return;
    if (_YBRPlugin.SYSTEM_FIELDS.has(fieldName.toLowerCase()))
      return;
    const activeFile = this.app.workspace.getActiveFile();
    const fm = activeFile ? (_a = this.app.metadataCache.getFileCache(activeFile)) == null ? void 0 : _a.frontmatter : null;
    const caseCorrectFieldName = fm ? Object.keys(fm).find((k) => k.toLowerCase() === fieldName.toLowerCase()) || fieldName : fieldName;
    const isInAnyPair = RelationCache.isFieldInPairs(
      caseCorrectFieldName,
      this.getActivePairs()
    );
    this.menuManager.closeAndFlush();
    this.menuManager.addItem(
      (item) => item.setTitle(isInAnyPair ? t("menu.editPair") : t("menu.configurePair")).setIcon("link").onClick(() => {
        this.onPropertyButtonClick(caseCorrectFieldName);
      })
    );
  }
  /**
   * Get the counterpart field name for display purposes.
   */
  getPairCounterparts(fieldName) {
    const counterparts = [];
    for (const pair of this.settings.pairs) {
      if (pair.fieldA === fieldName)
        counterparts.push(pair.fieldB);
      else if (pair.fieldB === fieldName)
        counterparts.push(pair.fieldA);
    }
    return counterparts;
  }
  /**
   * Handle click on a property relation button.
   */
  async onPropertyButtonClick(fieldName) {
    var _a, _b;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile)
      return;
    const currentFm = (_a = this.app.metadataCache.getFileCache(activeFile)) == null ? void 0 : _a.frontmatter;
    const currentTags = (() => {
      if (!currentFm)
        return [];
      const raw = currentFm.tags;
      if (typeof raw === "string")
        return [raw];
      if (Array.isArray(raw))
        return raw.filter((x) => typeof x === "string");
      return [];
    })();
    const pageFields = currentFm ? Object.keys(currentFm).filter(
      (k) => !_YBRPlugin.SYSTEM_FIELDS.has(k) && k !== "position"
    ) : [];
    const activePairs = this.getActivePairs();
    const result = await showPairSuggestModal(
      this.app,
      fieldName,
      activeFile.basename,
      activePairs,
      currentTags,
      pageFields
    );
    if (result.action === "save" && result.counterpartField) {
      const counterpartField = result.counterpartField;
      if (result.sourceTag) {
        this.syncing.add(activeFile.path);
        try {
          await this.app.vault.process(activeFile, (content) => {
            const split = splitFrontmatter(content);
            if (split) {
              const hasTagsField = split.yaml.split("\n").some(
                (line) => line.startsWith("tags:") || line.startsWith("tags :")
              );
              if (!hasTagsField) {
                return content.replace(
                  /^(---\n)/,
                  `---
tags:
  - ${result.sourceTag}
`
                );
              }
            }
            return content;
          });
        } finally {
          setTimeout(() => this.syncing.delete(activeFile.path), 500);
        }
        currentTags.push(result.sourceTag);
      }
      const alreadyExists = this.settings.pairs.some(
        (p) => p.fieldA === fieldName && p.fieldB === counterpartField || p.fieldA === counterpartField && p.fieldB === fieldName
      );
      if (!alreadyExists) {
        this.settings.pairs.push({
          fieldA: fieldName,
          fieldB: counterpartField,
          tagA: currentTags[0] || "",
          tagB: result.counterpartTag || counterpartField
        });
        await this.saveSettings();
      }
      new import_obsidian6.Notice(t("notice.pairCreated", fieldName, counterpartField));
      const fm = (_b = this.app.metadataCache.getFileCache(activeFile)) == null ? void 0 : _b.frontmatter;
      if (fm) {
        const targets = extractTargets(fm[fieldName]);
        const sourceDisplay = this.settings.useDisplayName ? this.cache.getDisplayName(activeFile.basename) : null;
        for (const targetName of targets) {
          const targetFile = this.app.metadataCache.getFirstLinkpathDest(targetName, activeFile.path);
          if (!targetFile) {
            new import_obsidian6.Notice(t("notice.fileNotFound", targetName));
            continue;
          }
          const newLink = buildWikilink(activeFile.basename, sourceDisplay);
          this.syncing.add(targetFile.path);
          try {
            await this.app.vault.process(targetFile, (content) => {
              const yaml = extractYaml2(content);
              const existing = readFieldWikilinks(yaml, counterpartField);
              if (hasLinkTo(existing, activeFile.basename)) {
                return content;
              }
              const updated = [...existing, newLink];
              return updateFieldInContent(content, counterpartField, updated);
            });
            new import_obsidian6.Notice(t("notice.backlinkAdded", targetFile.basename, counterpartField, newLink));
          } finally {
            setTimeout(() => this.syncing.delete(targetFile.path), 500);
          }
        }
      }
      this.rebuildCache();
    } else if (result.action === "remove" && result.counterpartField) {
      this.settings.pairs = this.settings.pairs.filter(
        (p) => !(p.fieldA === fieldName && p.fieldB === result.counterpartField || p.fieldA === result.counterpartField && p.fieldB === fieldName)
      );
      await this.saveSettings();
      this.rebuildCache();
      new import_obsidian6.Notice(t("notice.pairRemoved", fieldName));
    }
  }
  // ─── File Event Handlers ────────────────────────────────────
  /**
   * Debounced file modify handler (300ms per file).
   */
  debouncedOnFileModify(file) {
    const existing = this.debounceTimers.get(file.path);
    if (existing)
      clearTimeout(existing);
    const timer = setTimeout(() => {
      this.debounceTimers.delete(file.path);
      this.onFileModify(file);
    }, 300);
    this.debounceTimers.set(file.path, timer);
  }
  /**
   * Handle file modification: detect relation changes and sync.
   */
  async onFileModify(file) {
    var _a;
    if (this.syncing.has(file.path))
      return;
    const activePairs = this.getActivePairs();
    if (!this.settings.autoSync || activePairs.length === 0)
      return;
    const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
    const watchedFields = RelationCache.getWatchedFields(
      activePairs
    );
    const changes = detectChanges(
      file.path,
      file.basename,
      fm,
      this.cache,
      activePairs
    );
    if (changes.length > 0) {
      if (this.settings.debug) {
        console.log(`[YBR] Changes detected in ${file.path}:`, changes);
      }
      await applyChanges(
        changes,
        this.app.vault,
        this.app.metadataCache,
        this.cache,
        this.syncing,
        this.settings.debug,
        this.settings.useDisplayName
      );
    }
    this.cache.updateFileRelations(file.path, fm, watchedFields);
    this.cache.updateDisplayName(
      file.basename,
      resolveDisplayName(fm)
    );
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile && activeFile.path === file.path) {
    }
  }
  /**
   * Handle new file creation.
   */
  async onFileCreate(file) {
    if (!this.settings.autoSync)
      return;
    if (!this.layoutReady)
      return;
    setTimeout(async () => {
      var _a, _b;
      const activePairs = this.getActivePairs();
      const watchedFields = RelationCache.getWatchedFields(
        activePairs
      );
      const fm = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter;
      this.cache.updateFileRelations(file.path, fm, watchedFields);
      this.cache.updateDisplayName(
        file.basename,
        resolveDisplayName(fm)
      );
      const newFileName = file.basename;
      const linkingFiles = this.cache.findFilesLinkingTo(
        file,
        this.app.metadataCache
      );
      if (linkingFiles.length > 0) {
        this.syncing.add(file.path);
        try {
          let autoTag = null;
          await this.app.vault.process(file, (content) => {
            var _a2;
            let result = content;
            for (const { filePath: srcPath, fieldName: srcField } of linkingFiles) {
              const srcFile = this.app.vault.getAbstractFileByPath(srcPath);
              if (!(srcFile instanceof import_obsidian6.TFile))
                continue;
              const srcFm = (_a2 = this.app.metadataCache.getFileCache(srcFile)) == null ? void 0 : _a2.frontmatter;
              const srcTags = (() => {
                if (!srcFm)
                  return [];
                const raw = srcFm.tags;
                if (typeof raw === "string")
                  return [raw];
                if (Array.isArray(raw))
                  return raw.filter((x) => typeof x === "string");
                return [];
              })();
              const counterpart = RelationCache.getCounterpartField(
                srcField,
                activePairs,
                srcTags
              );
              if (!counterpart)
                continue;
              const yaml = extractYaml2(result);
              const existing = readFieldWikilinks(yaml, counterpart.counterpartField);
              const srcBasename = srcFile.basename;
              if (!hasLinkTo(existing, srcBasename)) {
                const srcDisplay = this.settings.useDisplayName ? this.cache.getDisplayName(srcBasename) : null;
                const newLink = buildWikilink(srcBasename, srcDisplay);
                const updated = [...existing, newLink];
                result = updateFieldInContent(result, counterpart.counterpartField, updated);
                if (this.settings.debug) {
                  console.log(
                    `[YBR] New file ${newFileName}: added ${counterpart.counterpartField}: ${newLink} (from ${srcBasename}.${srcField})`
                  );
                }
              }
              if (!autoTag) {
                autoTag = counterpart.pair.fieldA === srcField ? counterpart.pair.tagB : counterpart.pair.tagA;
              }
            }
            if (autoTag) {
              const split = splitFrontmatter(result);
              if (split) {
                const hasTagsField = split.yaml.split("\n").some(
                  (line) => line.startsWith("tags:")
                );
                if (!hasTagsField) {
                  result = result.replace(
                    /^(---\n)/,
                    `---
tags:
  - ${autoTag}
`
                  );
                }
              }
            }
            return result;
          });
          const updatedFm = (_b = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _b.frontmatter;
          this.cache.updateFileRelations(file.path, updatedFm, watchedFields);
          this.cache.updateDisplayName(file.basename, resolveDisplayName(updatedFm));
          new import_obsidian6.Notice(t("notice.backlinksCreated", newFileName, String(linkingFiles.length)));
        } finally {
          setTimeout(() => this.syncing.delete(file.path), 500);
        }
      }
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile && activeFile.path === file.path) {
      }
    }, 800);
  }
};
var YBRPlugin = _YBRPlugin;
/** Frontmatter fields that should never show the relation button */
YBRPlugin.SYSTEM_FIELDS = /* @__PURE__ */ new Set([
  "title",
  "aliases",
  "tags",
  "cssclasses",
  "publish",
  "permalink",
  "description",
  "image",
  "cover",
  "banner",
  "date",
  "created",
  "updated",
  "modified",
  "position"
]);
